# The Displayname.
name=Terminal

# The application's service.
service=admin_panel,user_panel

# Physical path: /usr/local/lsws/Example/html/mypanel/3rdparty/index.php
# Literal URL path: $server:$port/3rdparty/plugin_folder/name/index.php
url=/module/terminal/gui/
#auto_login_url=/3rdparty/terminal/index.html

# pass paramter with header
#header[HTTP_AUTOLOGINUSER]=%email%
#header[HTTP_AUTOLOGINPASS]=%email_password%

# System user and group to run process as
user=nobody
group=nogroup

# Features required

features=advance

# Media  required
icon=/media/icon/terminal.svg

#short
sorder=1
